// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11j6nSUjA-OR_dFU5rIjw-Fsr3r3a2zg',
    appId: '1:271521513447:web:f2b9dd3f6a7ec2560f8742',
    messagingSenderId: '271521513447',
    projectId: 'to-do-list-d1531',
    authDomain: 'to-do-list-d1531.firebaseapp.com',
    storageBucket: 'to-do-list-d1531.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVmZxybMdy6XO8OaNbL9vb1OOlJVTioCY',
    appId: '1:271521513447:android:278731a22a61f4110f8742',
    messagingSenderId: '271521513447',
    projectId: 'to-do-list-d1531',
    storageBucket: 'to-do-list-d1531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnD44LtVTNG8CcDODrBZBHd2I7LyrtCE',
    appId: '1:271521513447:ios:ca63152e63bfab8e0f8742',
    messagingSenderId: '271521513447',
    projectId: 'to-do-list-d1531',
    storageBucket: 'to-do-list-d1531.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA11j6nSUjA-OR_dFU5rIjw-Fsr3r3a2zg',
    appId: '1:271521513447:web:a18953bea4102ffa0f8742',
    messagingSenderId: '271521513447',
    projectId: 'to-do-list-d1531',
    authDomain: 'to-do-list-d1531.firebaseapp.com',
    storageBucket: 'to-do-list-d1531.firebasestorage.app',
  );
}
